{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="border-box"><div class="tl"><div class="tr"><div class="br"><div class="bl"><div class="box-content float-break">
	<div class="border-ml"><div class="border-mr"><div class="border-mc">

<form action={concat($module.functions.password.uri,"/",$userID)|ezurl} method="post" name="Password">

    {def $changed = false()}
    {if $message}
        {if or($oldPasswordNotValid,$newPasswordNotMatch,$newPasswordNotValidate,$newPasswordMustDiffer)}
            {if $oldPasswordNotValid}
                <div class="warning">
                    <h2>La vecchia password non &egrave; corretta</h2>
                </div>
            {/if}
            {if $newPasswordNotMatch}
                <div class="warning">
                    <h2>La nuova password non corrisponde: fai attenzione nel compilare il campo "Riscrivi la NUOVA password"</h2>
                </div>
            {/if}
            {if $newPasswordNotValidate}
                <div class="warning">
                    <h2>La password che hai inserito non &egrave; valida. Scegline un'altra</h2>
                </div>
            {/if}
            {if $newPasswordMustDiffer}
                <div class="warning">
                    <h2>La nuova password deve essere diversa da quella vecchia</h2>
                </div>
            {/if}                    
        {else}
            <div class="message-feedback">
                <h2>Password modificata correttamente!</h2>
            </div>
            {set $changed = true()}
        {/if}
    {/if}
    
{if $changed|not()}
    <div class="attribute-header">
        <h1>Devi cambiare la password!</h1>
    </div>

    <div class="block">        
        <label>{if $oldPasswordNotValid}* {/if}Scrivi la vecchia password</label><div class="labelbreak"></div>
        <input type="password" class="halfbox" name="oldPassword" size="11" value="{$oldPassword}" />
    </div>
    
    <div class="block">        
        <label>{if or($newPasswordNotMatch,$newPasswordNotValidate)}* {/if}Scrivi la NUOVA password</label><div class="labelbreak"></div>
        <input class="halfbox"  type="password" name="newPassword" size="11" value="{$newPassword}" />
    </div>
    <div class="block">        
        <label>{if or($newPasswordNotMatch,$newPasswordNotValidate)}* {/if}Riscrivi la NUOVA password</label><div class="labelbreak"></div>
        <input class="halfbox" type="password" name="confirmPassword" size="11" value="{$confirmPassword}" />
    </div>
    
    <div class="buttonblock">
        <input class="defaultbutton" type="submit" name="OKButton" value="{'OK'|i18n('mbpaex/userpaex')}" />
        <input class="button" type="submit" name="CancelButton" value="{'Cancel'|i18n('mbpaex/userpaex')}" />
    </div>
{else}
    {def $redirect = '/'}
    {if ezhttp_hasvariable( 'RedirectAfterPasswordChange', 'session' )}
        {set $redirect = ezhttp( 'RedirectAfterPasswordChange', 'session' )}
    {/if}
    <a class="defaultbutton" href="{$redirect}">Vai al sito</a>
{/if}

</form>

</div></div></div>
</div></div></div></div></div></div>
