{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="border-box"><div class="tl"><div class="tr"><div class="br"><div class="bl"><div class="box-content float-break">
	<div class="border-ml"><div class="border-mr"><div class="border-mc">

{if $link}
    <div class="attribute-header">
        <h1>Controlla la posta elettronica</h1>
    </div>
    <p>
        E' stata inviata una mail all'indirizzo: {$email}. <br />
        L'email contiene il link per generare una nuova password.
    </p>
{else}
    {if $wrong_email}
        <div class="warning">
            <h2>Non ci sono utenti con questo indirizzo email</h2>
        </div>
    {/if}
    {if $password_form}
        {if $password_changed}
            <div class="message-feedback">
            <h2>
                La password &egrave; stata cambiata con successo.
            </h2>
            </div>
            <p><a class="defaultbutton" href="/">Vai al sito</a></p>
        {else}
            {if $newPasswordNotMatch}
                <div class="warning">
                    <h2>Inserisci la stessa password in entrambi i campi.</h2>
                </div>
            {/if}
            {if $newPasswordNotValidate}
                <div class="warning">
                    <h2>La password non &egrave valida. Scegline un'altra</h2>
                </div>
            {/if}
            {if $newPasswordMustDiffer}
                <div class="warning">
                    <h2>La nuova password deve essere diversa da quella vecchia. Scegline un'altra.</h2>
                </div>
            {/if}                    
           
            <form method="post" name="forgotpassword" action={concat("/userpaex/forgotpassword/",$HashKey)|ezurl}>
                <div class="attribute-header">
                    <h1>Scegli una nuova password</h1>
                </div>
                
                
                <div class="block">
                    <label for="password">Password:</label>
                    <div class="labelbreak"></div>
                    <input class="halfbox" type="password" name="NewPassword" size="20" value="" />
                    <label for="password">Conferma password:</label>
                    <div class="labelbreak"></div>
                    <input class="halfbox" type="password" name="NewPasswordConfirm" size="20" value="" />
                </div>
                
                <div class="buttonblock">
                    <input class="button" type="submit" name="ChangePasswdButton" value="OK" />
                    <input type="hidden" name="HashKey" value="{$HashKey}" />
                </div>
            </form>
        {/if}
    {else}
        {if $wrong_key}
            <div class="warning">
                <h2>Chiave non valida o gi&agrave; usata</h2>
            </div>
        {else}
            <form method="post" name="forgotpassword" action={"/userpaex/forgotpassword/"|ezurl}>
                <div class="attribute-header">
                    <h1>Password dimenticata?</h1>
                </div>
                
                <p>
                    Se hai dimenticato la password possiamo generartene una nuova. Tutto quello che devi fare &egrave; inserire il tuo indirizzo di posta elettronica.
                </p>
                
                <div class="block">
                    <label for="email">{"Email"|i18n('mbpaex/userpaex/forgotpassword')}:</label>
                    <div class="labelbreak"></div>
                    <input class="halfbox" type="text" name="UserEmail" size="40" value="{$wrong_email|wash}" />
                </div>
                
                <div class="buttonblock">
                    <input class="button" type="submit" name="GenerateButton" value="Genera una nuova password" />
                </div>
            </form>
        {/if}
    {/if}
{/if}

</div></div></div>
</div></div></div></div></div></div>
